### ISSUE TITLE
Custom axis tags don't conform to OT spec

### ISSUE THREAD

**Issue by PeterCon** [TypeNetwork/fb-Decovar#2]
The Decovar font defines axes in the 'fvar' table using these axis tags:

bldA
bldB
sklA
sklB
sklD
trmA
trmB
trmC
trmD
trmE
trmF
trmG
trmK
trmL
wmx2

This doesn't conform to the OT spec requirements for custom axis tags:

"Privately-defined axis tags must begin with an uppercase letter (0x41 to 0x5A), and must use only uppercase letters or digits."

See here for full details on axis tags requirements:
https://www.microsoft.com/typography/otspec/fvar.htm

**Comment by dberlow** [comment]
Yes. We are publicly defining them here in an open source font;) Decovar though, so most of them don't matter much as neither the user value, or the name has meaning. As such, visual representation of it is required. wmx2, on the other hand, is shared with Amstelvar, where All of the Axes we have  publicly defined in an open source font, have meaningful axes names and values to users and applications, will require interoperability, and should IMO, be registered as well as being public as they now are.

**Comment by PeterCon** [comment]
David:

If you think that “wmx2” should be a registered tag, then I suggest you float the idea on the OpenType list and/or on TypeDrawers, providing details about the axis and the values that it uses, as required by the OT spec ([here](https://www.microsoft.com/typography/otspec/fvar.htm)):

> Every registered tag provides a US English name for the axis that can be used as a display string in user interfaces to refer to the axis, or as the basis of localized display strings.
>
> Every registered tag also provides information regarding the range of valid values for that axis. Depending on the axis, this may or may not be a bounded range. Every registered tag must also provide information regarding the scale for those values, specifying either some objective measure or some convention by which values can be interpreted. This is required to provide some means if interoperability between different fonts and between OpenType Font Variations and other specifications, such as font-weight values in CSS.”

Let’s see what response it gets from others.

**Comment by dberlow** [comment]
Dear Peter, 

I thank you for that suggestion, and sometime soon, I hope to take you up on it. I've been quiet since your comment about bold and condensed needing to be added together. 

So, I'm now working on not only explaining what I've done in each font, and why, but also variations themselves. 

That will appear here, not as an appeal for support, but just so people know what we have done and demonstrated, are doing now, and going forward with. If they don't want to go that way, they don't have to. 

And if our direction is not compatible with the spec, then those who follow the spec will not be able to go where we've demonstrated. If you want grades, you will follow us — or go ahead, wait in vain until someone else demonstrates grades that really work.

Thanks

**Comment by djrrb** [comment]
Hi @PeterCon we just committed a new version of Decovar with a new axis-naming scheme. Hopefully these address the concerns you had about the naming of the original axes.

I suppose I can close this issue because I think the original question was resolved, but feel free to reopen and commit should it warrant any more discussion. Thank you!

**Comment by davelab6** [comment]
Thanks​ djr!!

On Apr 3, 2017 2:19 PM, "David Jonathan Ross" <notifications@github.com>
wrote:

Closed #2 <https://github.com/TypeNetwork/fb-Decovar/issues/2>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TypeNetwork/fb-Decovar/issues/2#event-1027005310>, or mute
the thread
